version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-practice
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - '3000:3000'

  db:
    image: mysql:8.0.28
    container_name: nest-practice-db
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      TZ: Asia/Tokyo
    ports:
      - '${MYSQL_PORT}:3306'

    volumes:
      # ホスト:コンテナ
      # 初期データを投入するSQLが格納されているdir
      - ./docker/db/sql:/docker-entrypoint-initdb.d
      # DBのデータの実体
      - ./docker/db/mysql:/var/lib/mysql
      # 設定ファイル
      - ./docker/db/my.cnf:/etc/mysql/my.cnf

      - ./mysql-files:/var/lib/mysql-files
